language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails41.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
before_install: gem install bundler
script: bundle exec rake test
addons:
  code_climate:
    repo_token:
      secure: "hnJNNpijc+EzRvg1zImLm8mZXMOllBkS4CuEMQLXr9fKB24RyHvlw7IF/fkh6YlMHpmz4aQOO593+hl2Gl56lGnIuJQtqulcyeYQgiPYGvl4zQVgYM4cVfHyIvM0cin68NPrUaqnF51sejKQrfLEMJuQFn0MvB2ZKviRNUQ5Bj9dfj+hz03clYfgNaZh4DHrd/YwHGA+vfnD24GMNPI2VXkg4CUzb2ViupfjwxceEDLTiIMQNvEfkhPMiFeK13Z/IsOoBkkCcafyD9Mqm6f8gVyV1E0ErrSMzfJZ0EMzLSrKzotdp+ZCLpic9aENcQIMmZsNlNpgSZPRWA+RBpi+LdaTbXx8zQCSQFbrP4p1PzuCug4FMq9NYTGdadrsKhAv62Piv3A6XbYbI5Dzo1Qe6bvkAFeFulH29F/ToZ8OtKLvIq3osnUWgrWijfeg0lYeGc1uwq8aRV2HSLGLYJyq61hWBbMm5bQzMM41h8LnBbh6euAtg2e6bxd+H69pm2nULzmPHfSuwWie/tAvCM+rgrfgYatI3/FuuyNblJpGars1bDCBKYh0Nj717hMkGZ1KU4mj31+oDM9na6E0uY96FYWu8TwWAwcYlmxT0hAUUff6VCWQc8yD2apt0Cphi9//Gs374u9EW3/BhZXGkRRXuMaAdlGpOcwA27FsCqHOTGk="
