language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  - exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails41.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
before_install: gem install bundler
script: bundle exec rake test
